# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # allows you to trigger manually


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: setup-env-${{matrix.os}}-python-${{matrix.python-version}}
    runs-on: ${{ matrix.os }} #, macos-latest, windows-latest]
    strategy:
      #max-parallel: 1
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
      with:
        path: main


    - name: Checkout pyfesom2 
      uses: actions/checkout@v3
      with:
        repository: FESOM/pyfesom2
        path: pyfesom2
        fetch-depth: 0

    - name: install conda environment
      uses: mamba-org/provision-with-micromamba@main #/v12
      with:
        environment-file: main/ci/requirements-py37.yml
        environment-name: pyfesom2
        cache-env: true
        cache-env-key: "${{runner.os}}-${{runner.arch}}-py${{env.PYTHON_VERSION}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"

    - name: Checkout git commit log 
      working-directory: pyfesom2
      run: |
        #            git checkout suvi_fix_github_workflow
            git log

    - name: Checkout xarray version
      run: |
        python -c "import xarray; print('xarray version:', xarray.__version__)"
        python -c "import netCDF4; print('netcdf4 (py,c) versions:', netCDF4.__version__, netCDF4._netCDF4.__netcdf4libversion__)"

    - name: Install pyfesom2
      working-directory: pyfesom2
      run: |
            python -m pip install -e .

    - name: Test pyfesom2 import
      working-directory: pyfesom2
      run: |
            python -c "import pyfesom2"

    - name: Test pyfesom2
      working-directory: pyfesom2
      run: |
            python -m pytest -n 4 tests/test_accessor.py

