# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # allows you to trigger manually


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: setup-env-${{matrix.os}}-${{matrix.python-version}}
    runs-on: ${{ matrix.os }} #, macos-latest, windows-latest]
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: install conda environment
      uses: mamba-org/provision-with-micromamba@main #/v12
      with:
        environment-file: ci/requirements-py37.yml
        environment-name: pyfesom2
        cache-env: true
        cache-env-key: "${{runner.os}}-${{runner.arch}}-py${{env.PYTHON_VERSION}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
    - name: Checkout pyfesom2 
      run: |
            git clone https://github.com/FESOM/pyfesom2 
    
    - name: Install pyfesom2
      working-directory: pyfesom2
      run: |
            python -m pip install -e .

    - name: Test pyfesom2 import
      working-directory: pyfesom2
      run: |
            python -c "import pyfesom2"

    - name: Test pyfesom2
      working-directory: pyfesom2
      run: |
            python -m pytest

